spring:
  datasource:
    url: jdbc:mysql:///mybatisdb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.226.130
  cache:
    type: redis
    redis:
      time-to-live: 60000
mybatis:
  mapper-locations: classpath:com/qf/stu/student_demo/dao/mapper/*.xml
  type-aliases-package: com.qf.stu.student_demo.entity