package com.qf.oa.dao;

import com.qf.oa.entity.Caigou;

import java.util.List;

public interface CaigouMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated
     */
    int insert(Caigou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated
     */
    int insertSelective(Caigou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated
     */
    Caigou selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Caigou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caigou
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Caigou record);


    List<Caigou> queryByEid(Integer eid);
}